Module5 task1
htmlacademy-adaptive/1981559-sedona-27 pull request #5
Opened 2022-12-18 09:28 UTC by VladissGernet

2022-12-19 13:28 UTC, Dima-Dim requested changes

2022-12-19 13:28 UTC, Dima-Dim commented on source/catalog.html
> +    <a class="main-footer__developed-by-link special-link special-link" href="#">
`special-link special-link` - чтобы прям наверняка? :)

2022-12-19 13:28 UTC, Dima-Dim commented on source/form.html
> +      <fieldset class="feedback-form__user feedback-form__user-information">
Тут скорее модификатор нужен, а не второй элемент.

2022-12-19 13:28 UTC, Dima-Dim commented on source/form.html
> +        <legend class="feedback-form__title">Посещенные<br> достопримечательности:</legend>
Почему перенос не за счёт ограничения ширины?

2022-12-19 13:28 UTC, Dima-Dim commented on source/form.html
> +          ОТПРАВИТЬ ОТЗЫВ
Почему оставил большие буквы в разметке?

2022-12-19 13:28 UTC, Dima-Dim commented on source/less/advantages.less
> +  .advantages__description {
Не нужно устраивать такую вложенность таким образом. Кода ниже это тоже касается.

2022-12-19 13:28 UTC, Dima-Dim commented on source/less/feedback-form.less
> +    .feedback-form__title {
Тоже не допустима вложенность c &.

2022-12-21 07:11 UTC, VladissGernet commented on source/less/advantages.less
> +  .advantages__description {
Не могу понять. Такая вложенность недопустима? 

`.advantages__item--inverted {
  @media (min-width: @tablet-width) {
    grid-template-columns: 512px 1fr;

    .advantages__title {
      grid-column: 2 / 3;
    }

    .advantages__number {
      grid-column: 2 / 3;
    }

    .advantages__description {
      grid-column: 2 / 3;
    }

    .advantages__image {
      grid-column: 1 / 2;
    }
  }`

2022-12-21 08:46 UTC, Dima-Dim commented on source/less/advantages.less
> +  .advantages__description {
Да. https://up.htmlacademy.ru/adaptive/27/criteries#d11

2022-12-22 03:51 UTC, merged